services:
  - type: web
    name: psx-rsi-dashboard
    runtime: node
    plan: starter
    region: singapore
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22.22.2
